### PR TITLE
Feature/angular storybook

### PR DESCRIPTION
**Pull request by emclaug2**
Changes proposed in this Pull Request:
- Refactored angular project structure from individual builds and configs, to a single mono structure
- Created angular storybook demo for existing components
- Linted, Prettier'd and refactored existing angular components
- Fixed issue in ChannelValue where font size was not being used
- Updated component library to angular 8

### CODE REVIEW

**Comment by huayunh** [comment]
need to rewrite the readme to include instructions for bringing up storybook

**Comment by huayunh** [comment]
Hero with ChannelValue children better look like this (from hero.md):
image
The current example is a bit confusing

**Comment by huayunh** [comment]
Should we still supply people with the label option when it is not affecting the demo result? Or we have to have something there bc it is part of the API?
image

**Comment by huayunh** [comment]
image
The menu looks very dark on my machine (My system is in dark theme, maybe that matters?)

**Comment by huayunh** [comment]
three dots button on the top left -> "About Your Storybook" gives "Oops! The latest version of Storybook couldn't be fetched." Might be an issue from Storybook.

**Comment by huayunh** [comment]
Hover / Clicking on any icon button (for example, zoom in/out glass, full screen) would cause the button to disappear (or, have eaton blue as the color css property).

**Comment by emclaug2** [comment]
> Should we still supply people with the label option when it is not affecting the demo result? Or we have to have something there bc it is part of the API?
> image

The label in this example was missing, it's been added so the knob is meaningful now.

**Comment by emclaug2** [comment]
> Hero with ChannelValue children better look like this, with the hour and minute units (from hero.md):
> image
> The current example is a bit confusing

I'm having a hard time getting the Hero Component to play nicely with my ChannelValue children.  This might be a defect within the Hero Component.

**Comment by joebochill** [comment]
> > Hero with ChannelValue children better look like this, with the hour and minute units (from hero.md):
> > image
> > The current example is a bit confusing
> 
> I'm having a hard time getting the Hero Component to play nicely with my ChannelValue children. This might be a defect within the Hero Component.

It's working as expected in the showcase, so it's probably a usage or a binding issue...try hardcoding the units and see if it works as expected.

**Comment by jeffvg** [comment]
Add knob for "action text" on empty state with action.
unable to upload image here still...

**Comment by jeffvg** [comment]
add in empty state notes, usage and API data

**Comment by joebochill** [comment]
I published a beta.0 version of the angular components in the current state to test out in a project

**Comment by jeffvg** [comment]
rename story sub-categories to match react story book for Empty State:
- with action > Actions
- as text only > Text Only
- as a placeholder > Placeholder

**Comment by jeffvg** [comment]
Hero with channel value children not displaying knob label field in example

**Pull request merged**
