### PR TITLE
Feature/react drawer

### PR DESCRIPTION
**Pull request by emclaug2**
Changes proposed in this Pull Request:
- Add Drawer component for React.
- Drawer component added to React Storybook & Showcase demo
-

### CODE REVIEW

**Comment by joebochill** [comment]
I've got some comments, but I'm going to constrain the first round to the general drawer and the header:

## Drawer Props
- The drawer should accept Header, Body, Subheader, Footer, etc. as children rather than taking the configuration for those pieces and object props. Look at how the ListItem from Material-UI is used as a reference.

Expected usage:
```
<Drawer 
    open={_isOpen} 
    onClose={() => _onClose()} 
    classes={_myClassOverrideObject1}
    {...otherDrawerSpecificProps}
>
    <DrawerHeader
        title={'MyTitle'}
        subtitle={'mySubtitle'}
        classes={_myClassOverrideObject2}
        {...otherHeaderProps}
    />
    <DrawerSubHeader
        renderComponent={<CustomSubheaderContent/>}
        classes={_myClassOverrideObject3}
        {...otherSubHeaderSpecificProps}
    />
    // In theory, you could pass in two DrawerBody components to achieve the 'pinned to the bottom' style
    <DrawerBody
        navigationGroups={_myRouteDefinitions}
        backgroundColor={'red'}
        classes={_myClassOverrideObject4}
        {...otherBodySpecificProps}
    />
    <DrawerFooter
        backgroundColor={'purple'}
        renderComponent={<CustomFooterContent/>}
        classes={_myClassOverrideObject5}
        {...otherFooterSpecificProps}
    />
</Drawer>
```

**Comment by joebochill** [comment]
## Drawer Behavior
- The drawer shouldn't maintain internal state for the open/closed state...this should be controlled explicitly through the `open` prop.
    - `open={true}` means the drawer is 'locked' open
    - `open={false}` means the drawer is in the collapsed state
- Hovering over the drawer when `open={false}` will expand the drawer temporarily, and it will go back to collapsed when the mouse leaves (hovered state will be managed inside the Drawer component)
- At mobile size open/closed equates to show/hide
- Clicking a route does not have to (i.e. shouldn't) automatically collapse the drawer...this logic should be left to the developer and determined through updating of the `open` prop on their end.
- Most of the functions and styles currently defined in the Header component can be moved down to the subcomponent where they are used (or a utility library) instead of passing them down through props.

**Comment by joebochill** [comment]
## Drawer Header
- Let's scrap the `info` prop from our 'standard' header to simplify the sizing
- Header should mimic the size of standard Material-UI toolbar so that it aligns with the body...currently it's jumbo even with just a title and subtitle:
    
image
- background image should be implemented in the same way as in the scorecard header, and how we did it for the React Native header
    - User should be able to have a background image and background color and have them blended
    - custom gradients will be handled via 'custom header component' approach

**Comment by emclaug2** [comment]
Drawer API has been edited to accept Header, Subheader, Body, & Footer elements as children.

**Pull request merged**
